version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
  cache:
    image: redis:alpine
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - '5341:5341'
      - '8081:80'
  henry.scheduling.api:
    image: ${DOCKER_REGISTRY-}henryschedulingapi
    build:
      context: .
      dockerfile: src/Henry.Scheduling.Api/Dockerfile
    depends_on:
      - db
      - cache
      - seq