version: '3.4'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=scheduling
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  cache:
    image: redis:alpine
    restart: always
    container_name: redis
    volumes:
      - ../data/redis:/data
    ports:
      - "6379:6379"
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - '5341:5341'
      - '8081:80'
  henry.scheduling.api:
    image: ${DOCKER_REGISTRY-}henryschedulingapi
    build:
      context: .
      dockerfile: src/Henry.Scheduling.Api/Dockerfile
    depends_on:
      - db
      - cache
      - seq